//! Lockfile writer.
//!
//! Serializes a lockfile to TOML with deterministic ordering.
//! Using BTreeMap in the schema guarantees that packages are always
//! sorted by canonical ID, producing identical output for identical state.

use crate::schema::Lockfile;
use std::path::Path;
use tracing::{debug, instrument};

/// Error type for lockfile writing.
#[derive(Debug, thiserror::Error)]
pub enum WriteError {
    #[error("failed to serialize lockfile: {0}")]
    Serialize(String),

    #[error("failed to write lockfile: {0}")]
    Io(#[from] std::io::Error),
}

/// Write a lockfile to a TOML string with deterministic ordering.
///
/// The output is deterministic because:
/// - Packages are stored in a BTreeMap (sorted by canonical ID)
/// - Dependencies within each package are sorted
/// - TOML serialization preserves insertion order for BTreeMap
pub fn write_lockfile(lockfile: &Lockfile) -> Result<String, WriteError> {
    // Pre-sort dependencies within each package for determinism.
    let mut sorted = lockfile.clone();
    for (_, pkg) in sorted.packages.iter_mut() {
        pkg.dependencies.sort_by(|a, b| a.canonical_id.cmp(&b.canonical_id));
    }

    let header = format!(
        "# This file is generated by rusk. Do not edit manually.\n\
         # Lockfile format version {}\n\n",
        sorted.version
    );

    let body = toml::to_string_pretty(&sorted)
        .map_err(|e| WriteError::Serialize(e.to_string()))?;

    Ok(format!("{}{}", header, body))
}

/// Write a lockfile to disk.
///
/// Creates the file if it doesn't exist, overwrites if it does.
/// The output is deterministic: the same lockfile state will always
/// produce byte-identical output.
#[instrument(skip(lockfile), fields(path = %path.display(), packages = lockfile.package_count()))]
pub fn save_lockfile(lockfile: &Lockfile, path: &Path) -> Result<(), WriteError> {
    debug!("writing lockfile with {} packages", lockfile.package_count());
    let content = write_lockfile(lockfile)?;
    std::fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::*;
    use rusk_core::*;

    #[test]
    fn write_empty_lockfile() {
        let lf = Lockfile::new();
        let output = write_lockfile(&lf).unwrap();
        assert!(output.contains("generated by rusk"));
        assert!(output.contains("version = 1"));
    }

    #[test]
    fn write_deterministic_order() {
        let mut lf = Lockfile::new();
        // Add packages in reverse alphabetical order.
        for name in ["zlib", "axios", "lodash"] {
            lf.add_package(LockedPackage {
                package: PackageId::js(name),
                version: Version::Semver(semver::Version::new(1, 0, 0)),
                ecosystem: Ecosystem::Js,
                digest: Sha256Digest::zero(),
                source_url: None,
                dependencies: vec![],
                dev: false,
                signer: None,
                provenance: None,
                resolved_by: None,
            });
        }

        let output1 = write_lockfile(&lf).unwrap();
        let output2 = write_lockfile(&lf).unwrap();
        assert_eq!(output1, output2, "lockfile output should be deterministic");

        // Verify alphabetical order in output: axios should come before lodash
        let axios_pos = output1.find("axios").unwrap();
        let lodash_pos = output1.find("lodash").unwrap();
        let zlib_pos = output1.find("zlib").unwrap();
        assert!(axios_pos < lodash_pos);
        assert!(lodash_pos < zlib_pos);
    }

    #[test]
    fn dependencies_sorted_in_output() {
        let mut lf = Lockfile::new();
        lf.add_package(LockedPackage {
            package: PackageId::js("parent"),
            version: Version::Semver(semver::Version::new(1, 0, 0)),
            ecosystem: Ecosystem::Js,
            digest: Sha256Digest::zero(),
            source_url: None,
            dependencies: vec![
                LockedDependency {
                    canonical_id: "js:registry.npmjs.org/zebra".to_string(),
                    kind: LockedDepKind::Normal,
                },
                LockedDependency {
                    canonical_id: "js:registry.npmjs.org/alpha".to_string(),
                    kind: LockedDepKind::Normal,
                },
            ],
            dev: false,
            signer: None,
            provenance: None,
            resolved_by: None,
        });

        let output = write_lockfile(&lf).unwrap();
        let alpha_pos = output.find("alpha").unwrap();
        let zebra_pos = output.find("zebra").unwrap();
        assert!(alpha_pos < zebra_pos);
    }

    #[test]
    fn roundtrip_write_parse() {
        let mut lf = Lockfile::new();
        lf.add_package(LockedPackage {
            package: PackageId::js("express"),
            version: Version::Semver(semver::Version::new(4, 18, 2)),
            ecosystem: Ecosystem::Js,
            digest: Sha256Digest::compute(b"express"),
            source_url: Some("https://registry.npmjs.org/express/-/express-4.18.2.tgz".to_string()),
            dependencies: vec![],
            dev: false,
            signer: None,
            provenance: None,
            resolved_by: None,
        });

        let output = write_lockfile(&lf).unwrap();
        // The output should be parseable (strip header comment lines).
        let body: String = output
            .lines()
            .filter(|l| !l.starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        let parsed: Lockfile =
            toml::from_str(&body).expect("written lockfile should be parseable");
        assert_eq!(parsed.package_count(), 1);
    }
}
